import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import testioLogo from "@/assets/testio-logo.png";

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/50 px-6 py-4">
        <div className="max-w-2xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate(-1)} className="text-muted-foreground hover:text-foreground">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <h1 className="text-lg font-bold text-foreground">Terms of Service</h1>
          </div>
          <img src={testioLogo} alt="Testio" className="w-8 h-8" />
        </div>
      </header>

      <div className="max-w-2xl mx-auto px-6 py-8 space-y-6 text-foreground text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold mb-2">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By accessing and using Testio ("the App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">2. Description of Service</h2>
          <p className="text-muted-foreground">
            Testio is an AI-powered study tool that converts uploaded documents (PDFs, text, images) into summarized notes, flashcards, quizzes, and AI-generated podcasts to help users study more effectively.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">3. User Accounts</h2>
          <p className="text-muted-foreground">
            You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate information during registration and to update it as necessary.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">4. User Content</h2>
          <p className="text-muted-foreground">
            You retain ownership of all content you upload to Testio. By uploading content, you grant Testio a limited license to process your content for the purpose of generating study materials. We do not share your content with third parties.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">5. Acceptable Use</h2>
          <p className="text-muted-foreground">
            You agree not to upload content that is illegal, harmful, or violates the intellectual property rights of others. You agree not to attempt to reverse engineer, hack, or disrupt the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">6. AI-Generated Content</h2>
          <p className="text-muted-foreground">
            Notes, flashcards, quizzes, and podcasts generated by Testio are created using AI and may contain inaccuracies. Users should verify AI-generated content and use it as a supplement to, not a replacement for, their own study efforts.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">7. Privacy</h2>
          <p className="text-muted-foreground">
            We take your privacy seriously. Your uploaded documents are processed securely and are not shared with third parties. Account deletion will permanently remove all your data from our servers.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">8. Limitation of Liability</h2>
          <p className="text-muted-foreground">
            Testio is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of the service, including but not limited to errors in AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">9. Changes to Terms</h2>
          <p className="text-muted-foreground">
            We reserve the right to modify these terms at any time. Continued use of the App after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold mb-2">10. Contact</h2>
          <p className="text-muted-foreground">
            If you have any questions about these Terms of Service, please contact us at{" "}
            <a href="mailto:Testio4171@gmail.com" className="text-primary hover:underline">Testio4171@gmail.com</a>.
          </p>
        </section>
      </div>
    </div>
  );
};

export default TermsOfService;
